### ISSUE TITLE
训练时的label index out of range问题

### ISSUE THREAD

**Issue by littletomatodonkey** [tonysy/Deep-Feature-Flow-Segmentation#4]
您好，我在训练的时候，一直提示index out of range，就是predict label那一块，我发现在在您的代码里有很多使用了`res_image_name = seg_pathes[1][:-len('_gtFine_labelTrainIds.png')]`的代码，这个`_gtFine_labelTrainIds.png`我在cityscape中没有看到，只看到了`_gtFine_labelIds.png`，想问一下您代码中的名字是根据感兴趣的类别自己重新生成的训练图像吗(label id一一映射过去，不感兴趣的类别都设置为255)？谢谢！

**Comment by tonysy** [comment]
You can use the convert the labelds into TrainIds with this repo:
https://github.com/mcordts/cityscapesScripts
