### ISSUE TITLE
when choosing current image and other neighbor image to train dff, why set the probability of choosing current frame and other neighbor frame the same?

### ISSUE THREAD

**Issue by Gus-Guo** [tonysy/Deep-Feature-Flow-Segmentation#5]
when choosing current image and other neighbor image to train dff, why set the probability of choosing current frame and other neighbor frame the same? As written in image.py(224)

**Comment by littletomatodonkey** [comment]
He sets the test method to test the mIOU with different time intervals. But when training the network, it needs to learn many time intervals' impact to the nwtwork to improve the network's generalization ability. I hope this can help you.

**Comment by tonysy** [comment]
I follow the training strategy of the original paper, @littletomatodonkey has given a good explanation.

**Comment by Gus-Guo** [comment]
Thanks. I got it.
