### ISSUE TITLE
Training DFF and cityscape data issue

### ISSUE THREAD

**Issue by CindyHXH** [tonysy/Deep-Feature-Flow-Segmentation#7]
Hi @tonysy ,

I was trying to run DFF using
`python ./experiments/deeplab_dff/deeplab_dff_train.py --cfg ./experiments/deeplab_dff/cfgs/deeplab_resnet_v1_101_cityscapes_segmentation_video.yaml
`

For data preparation, I have downloaded **gtFine_trainvaltest.zip (241MB)** and **leftImg8bit_trainvaltest.zip (11GB)**  and the folder has structure like

- data/cityscapes_video/gtFine

- data/cityscapes_video/leftImg8bit

However, when I try DFF it outputs error for missing data as following:

> ======== Step:1,Starting to load_gt_segdb =========
======== Total Number of images: 2975======
======== Starting to get gt_segdb ========
======== Starting to create gt_segdb ======
100%|███████████████████████████████████████| 2975/2975 [02:16<00:00, 21.73it/s]
========= Wrote gt segdb to ./data/cache/cityscape_video_leftImg8bit_train_gt_segdb.pkl
=====Start appending flipped images to segdb(./lib/imdb)=====
100%|█████████████████████████████████████| 2975/2975 [00:00<00:00, 6716.08it/s]
{'data': (1L, 3L, 768L, 1024L),
 'data_ref': (1L, 3L, 768L, 1024L),
 'eq_flag': (1L,),
 'label': (1L, 1L, 768L, 1024L)}
./model/pretrained_model/resnet_v1_101
lr 0.0005 lr_epoch_diff [40.336, 60.504] lr_iters [59999, 89999]
ref image path error, image not exists! ./data/cityscapes_video/leftImg8bit/train/tubingen/tubingen_000111_000016_leftImg8bit.png
ref image path error, image not exists! ./data/cityscapes_video/leftImg8bit/train/weimar/weimar_000100_000016_leftImg8bit.png
ref image path error, image not exists! ./data/cityscapes_video/leftImg8bit/train/weimar/weimar_000095_000016_leftImg8bit.png
ref image path error, image not exists! ./data/cityscapes_video/leftImg8bit/train/erfurt/erfurt_000102_000016_leftImg8bit.png

These image files are not stored in the zip file I downloaded from Cityscape website. I want to ask what kind of data you used to run DFF when you mentioned to **download cityscapes video data and put it into data/cityscapes_video**? Thank you very much.

**Comment by tonysy** [comment]
You need to download this file `leftImg8bit_sequence_trainvaltest.zip` from the official website, which needs request.

**Comment by CindyHXH** [comment]
Hi @tonysy ,

Can you tell me the package ID for this zip? I want to make a request via `https://www.cityscapes-dataset.com/file-handling/?packageID=XXXX` but do not know the ID. Thank you.

**Comment by CindyHXH** [comment]
Hi @tonysy,

No worries. I think I'll just to contact the team via email. Is this the way how you get the data? Thanks.

**Comment by tonysy** [comment]
Just contact the team and wait for the response. Good luck
